root = "."
tmp_dir = "tmp"

[build]
cmd = "go run ./cmd/server"
bin = "./tmp/main"
full_bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "yaml", "yml"]
exclude_dir = ["tmp", "vendor"]
delay = 500
stop_on_error = true

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"
